from PIL import Image, ImageDraw, ImageFont
import sys
try:
    if(sys.argv[1]=='PRIVATE USE'):
        im = Image.open("./public/certificate_script/certif.jpg")
        seal_image=Image.open("./public/certificate_script/seal.jpg")
        d = ImageDraw.Draw(im)
        location0=(1100,778)
        location1=(1211,815)
        location2 = (771, 1104)
        location3 = (765,1275)
        location4=(580,1334)
        location5=(1042,1334)
        location6=(510,1921)
        location7=(409,1960)
        location8=(350,1750)
        text_color = (0,0,0)
        font = ImageFont.truetype("arial.ttf", 25)
        d.text(location0, sys.argv[2], fill=text_color,font=font)
        d.text(location1,sys.argv[3], fill=text_color,font=font)
        d.text(location2, sys.argv[4], fill=text_color,font=font)
        d.text(location3,sys.argv[5], fill=text_color,font=font)
        d.text(location4,sys.argv[6], fill=text_color,font=font)
        d.text(location5,sys.argv[7], fill=text_color,font=font)
        d.text(location6,sys.argv[8], fill=text_color,font=font)
        d.text(location7,sys.argv[9], fill=text_color,font=font)
        d.text(location8,sys.argv[10], fill=text_color,font=font)
        im.paste(seal_image, (1020,1845))
        try:
            im.save(".\public\All_Licenses\License_"+sys.argv[2]+".pdf")
            print('{"status":true}')
        except:
            print('{"status":false}')
    else:
        im = Image.open("./public/certificate_script/public.jpg")
        seal_image=Image.open("./public/certificate_script/seal.jpg")
        d = ImageDraw.Draw(im)
        location0=(827,488)
        location1=(924,514)
        location2 = (581,757)
        location3 = (581,882)
        location4=(439,932)
        location5=(775,932)
        location6=(382,1430)
        location7=(306,1458)
        location8=(622,1426)
        text_color = (0,0,0)
        font = ImageFont.truetype("arial.ttf", 25)
        d.text(location0, sys.argv[2], fill=text_color,font=font)
        d.text(location1,sys.argv[3], fill=text_color,font=font)
        d.text(location2, sys.argv[4], fill=text_color,font=font)
        d.text(location3,sys.argv[5], fill=text_color,font=font)
        d.text(location4,sys.argv[6], fill=text_color,font=font)
        d.text(location5,sys.argv[7], fill=text_color,font=font)
        d.text(location6,sys.argv[8], fill=text_color,font=font)
        d.text(location7,sys.argv[9], fill=text_color,font=font)
        d.text(location8,sys.argv[10], fill=text_color,font=font)
        im.paste(seal_image, (639,1366))
        try:
            im.save(".\public\All_Licenses\License_"+sys.argv[2]+".pdf")
            print('{"status":true}')
        except:
            print('{"status":false}')
except:
    print("errr")                